steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/enhancing-model', 'Dash_App/Enhancing_Model']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/enhancing-model']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run',
        'deploy',
        'enhancing-model',
        '--image',
        'gcr.io/$PROJECT_ID/enhancing-model',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--allow-unauthenticated',
        '--port',
        '8501'
      ]

options:
  logging: CLOUD_LOGGING_ONLY
